import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { checkDbStatus } from "@/lib/checkDbStatus";
import Notice from "@/components/Notice"
import Footer from "@/components/Footer"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Gu3ss",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>){
  const db = await checkDbStatus();
  
  return (
    <html lang="en">
      <body>
        {!db.ok && (
  <Notice />
)}
        {db.ok && children}
        <Footer></Footer>
      </body>
    </html>
  );
}
